### ISSUE TITLE
Pleroma page returns 404

### ISSUE THREAD

**Issue by shadow-identity** [fedidb/issues#15]
**Describe the bug**
https://fedidb.org/software/pleroma returns 404 at least [since March](https://web.archive.org/web/20240324095259/https://fedidb.org/software/pleroma) 

**To Reproduce**
1. Go to https://fedidb.org/software/pleroma
2. See error

**Expected behavior**
Pleroma still exists, so should be shown.

**Screenshots**
<img width="838" alt="image" src="https://github.com/fedidb/issues/assets/1223112/9d432803-37f3-42ad-9731-5328c9632171">

**Comment by pepecyb** [comment]
...and the 404 error still exists. :-( For weeks!

**Comment by shadow-identity** [comment]
Not anymore
