### ISSUE TITLE
Sort instances by version

### ISSUE THREAD

**Issue by codenyte** [fedidb/issues#20]
**Is your feature request related to a problem? Please describe.**
Outdated instances might have security vulnerabilities

**Describe the solution you'd like**
Allow users to sort instances by version

**Describe alternatives you've considered**
Implement a toggle to only show instances running the latest version

**Additional context**
N/A

**Comment by mapto** [comment]
Probably close enough?
https://mastodon.social/@fedidb/111464877332659808
