### ISSUE TITLE
Lemmy software page is broken

### ISSUE THREAD

**Issue by kersploosh** [fedidb/issues#4]
**Describe the bug**
FediDB no longer shows the server and stats summary page for Lemmy.

**To Reproduce**
1. Go to [https://fedidb.org/software/lemmy](https://fedidb.org/software/lemmy)
2. See error "404 Software Not Found"

**Expected behavior**
I expected to see Lemmy user stats, and lists of Lemmy servers.

**Screenshots**
See attached screenshot.
<img width="917" alt="Screenshot 2024-01-30 130802" src="https://github.com/fedidb/issues/assets/145717012/437ee1a7-208e-4f85-a81a-582e9c879a18">

**Desktop (please complete the following information):**
The issue occurs in this browser...
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 112.0
... and also this browser.
 - OS: Windows 10
 - Browser: Chrome
 - Version: 114.0.5735.199

**Comment by bantryblues** [comment]
mastodon software page is broken in the same way

https://fedidb.org/software/mastodon

on iPadOS Safari browser (won’t list other details givenoriginal report

None of the software links work on

https://fedidb.org/software

**Comment by dansup** [comment]
Fixed!
